name: PartnerMirror
options:
  bundleIdPrefix: com.yourcompany
targets:
  PartnerMirror:
    type: application
    platform: iOS
    deploymentTarget: "13.0"
    sources:
      - path: Sources
    info:
      path: Info.plist
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.yourcompany.PartnerMirror
      SWIFT_VERSION: 5.0
      INFOPLIST_FILE: Info.plist
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    scheme:
      testTargets: []
