workflows:
  ios_simulator_build:
    name: iOS Simulator Build (check)
    environment:
      xcode: latest
    scripts:
      - name: Instalar XcodeGen
        script: brew install xcodegen
      - name: Gerar projeto Xcode
        script: xcodegen generate
      - name: Build para simulador (sem assinatura)
        script: |
          xcodebuild \
            -project PartnerMirror.xcodeproj \
            -scheme PartnerMirror \
            -sdk iphonesimulator \
            -configuration Debug \
            build
    artifacts:
      - ~/Library/Developer/Xcode/DerivedData/**/Build/Products/Debug-iphonesimulator/*.app

  ios_unsigned_ipa:
    name: iOS Unsigned IPA (sideload)
    environment:
      xcode: latest
    scripts:
      - name: Instalar XcodeGen
        script: brew install xcodegen
      - name: Gerar projeto Xcode
        script: xcodegen generate
      - name: Build iPhoneOS sem assinatura
        script: |
          xcodebuild \
            -project PartnerMirror.xcodeproj \
            -scheme PartnerMirror \
            -configuration Release \
            -sdk iphoneos \
            -derivedDataPath $CM_BUILD_DIR/DD \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_IDENTITY="" \
            clean build
      - name: Empacotar IPA
        script: |
          APP_PATH="$CM_BUILD_DIR/DD/Build/Products/Release-iphoneos/PartnerMirror.app"
          mkdir -p Payload
          cp -R "$APP_PATH" Payload/PartnerMirror.app
          zip -r PartnerMirror-unsigned.ipa Payload
    artifacts:
      - PartnerMirror-unsigned.ipa
