workflows:
  ios_simulator_build:
    name: iOS Simulator Build (check)
    environment:
      xcode: latest
    scripts:
      - name: Clean & regen
        script: |
          rm -rf PartnerMirror.xcodeproj
          rm -rf ~/Library/Developer/Xcode/DerivedData
          brew install xcodegen
          xcodegen generate
      - name: Build for iOS Simulator
        script: |
          xcodebuild \
            -project PartnerMirror.xcodeproj \
            -scheme PartnerMirror \
            -sdk iphonesimulator \
            -configuration Debug \
            build
    artifacts:
      - ~/Library/Developer/Xcode/DerivedData/**/Build/Products/Debug-iphonesimulator/*.app
