workflows:
  ios_simulator_build:
    name: iOS Simulator Build (check)
    environment:
      xcode: latest
    scripts:
      # NOVO PASSO: Limpa caches para evitar falhas persistentes de build
      - name: Limpar caches do Xcode
        script: |
          rm -rf ~/Library/Developer/Xcode/DerivedData
          rm -rf build
          
      - name: Instalar XcodeGen
        script: brew install xcodegen
      - name: Gerar projeto Xcode
        script: xcodegen generate
      - name: Build para simulador (sem assinatura)
        script: |
          xcodebuild \
            -project PartnerMirror.xcodeproj \
            -scheme PartnerMirror \
            -sdk iphonesimulator \
            -configuration Debug \
            build
    artifacts:
      - ~/Library/Developer/Xcode/DerivedData/**/Build/Products/Debug-iphonesimulator/*.app
